### ISSUE TITLE
fix ERROR [list-config-history] error

### ISSUE THREAD

**Issue by sunyitao** [wuchubuzai2018/nacos-datasource-extend-plugins#5]
ERROR [list-config-history] error, dataId:[uaas-service.yaml, DEFAULT_GROUP], group:{}

org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [SELECT nid,data_id,group_id,tenant_id,app_name,src_ip,src_user,op_type,gmt_create,gmt_modified FROM his_config_info WHERE data_id = ? AND group_id = ? AND tenant_id = ? ORDER BY nid DESC  LIMIT 0,10]; nested exception is org.postgresql.util.PSQLException: ERROR: LIMIT #,# syntax is not supported
  Hint: Use separate LIMIT and OFFSET clauses.

可否加入  [collaborator](https://github.com/wuchubuzai2018/nacos-datasource-extend-plugins/settings/access?query=filter%3Acollaborators) ，把修改代码提交上去。

**Comment by fqjedu** [comment]
请问是怎样解决的，我整合 pg 后，nacos 查询不到历史版本

**Comment by sunyitao** [comment]
修改实现类：com\alibaba\nacos\plugin\datasource\impl\postgresql\HistoryConfigInfoMapperByPostgresql.java

**Comment by wuchubuzai2018** [comment]
建议大于2.2.0的版本用官方的的PG插件库维护分支，之前我这个代码已经贡献给官方的PG分支，不在维护
