### ISSUE TITLE
配置管理 历史版本 查询不出来

### ISSUE THREAD

**Issue by fqjedu** [wuchubuzai2018/nacos-datasource-extend-plugins#7]
我按照教程整合 pg 后，发现 nacos 界面查询不出配置管理的历史版本信息，但是数据中是有历史版本的记录的
![image](https://github.com/wuchubuzai2018/nacos-datasource-extend-plugins/assets/86455835/d12dd516-529b-4fdc-926e-9d9a0ffc239b)
![image](https://github.com/wuchubuzai2018/nacos-datasource-extend-plugins/assets/86455835/020b2a3e-7597-4435-b14f-6b70aa1fd696)

**Comment by xn12134** [comment]
我也遇到这个问题 是pgsql的分页查询原因 ，具体怎么改我也不清楚 ，不熟悉java ,望博主改下 很急
![image](https://github.com/wuchubuzai2018/nacos-datasource-extend-plugins/assets/68426269/eff944cd-7753-4804-965d-145425f4fb6a)
![image](https://github.com/wuchubuzai2018/nacos-datasource-extend-plugins/assets/68426269/68319411-2e7f-4a91-89fd-565d1e610ae3)

**Comment by wuchubuzai2018** [comment]
建议大于2.2.0的版本用官方的的PG插件库维护分支，之前我这个代码已经贡献给官方的PG分支，不在维护

**Comment by fqjedu** [comment]
> 建议大于2.2.0的版本用官方的的PG插件库维护分支，之前我这个代码已经贡献给官方的PG分支，不在维护

可否把官方pg分支的链接贴一下
